# Generated by Django 5.2.9 on 2025-12-14 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pet',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='chip_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pet',
            name='neutered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_entries', to='pets.pet')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
