# Generated by Django 5.2.9 on 2025-12-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tutor',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
