# Generated by Django 5.2.9 on 2026-01-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_remove_business_user_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='business_banners/'),
        ),
    ]
