# Generated by Django 5.2.9 on 2026-01-05 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_business_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='PawCentral', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Trusted pet care service', max_length=255)),
                ('email', models.EmailField(blank=True, default='support@pawcentral.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+1 (555) 123-4567', max_length=20)),
                ('hours', models.CharField(blank=True, default='Mon-Fri 9 AM - 5 PM', max_length=100)),
                ('facebook_url', models.URLField(blank=True, default='#')),
                ('instagram_url', models.URLField(blank=True, default='#')),
                ('twitter_url', models.URLField(blank=True, default='#')),
                ('copyright_text', models.CharField(blank=True, default='All rights reserved. Built with ❤️ for pet lovers', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='footer_config', to='pets.business')),
            ],
            options={
                'verbose_name': 'Footer Configuration',
                'verbose_name_plural': 'Footer Configurations',
            },
        ),
    ]
