# Generated by Django 5.2.9 on 2025-12-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_woof_parent_woof_woof_tutor_alter_woof_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='woof',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='woof_attachments/'),
        ),
    ]
