# Generated by Django 5.2.9 on 2025-12-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_woof_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalwoof',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='woof_attachments/'),
        ),
    ]
