# Generated by Django 5.2.9 on 2025-12-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_globalwoof_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='woof',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private (to pet tutor)')], default='public', max_length=10),
        ),
    ]
