# Generated by Django 5.2.9 on 2026-01-04 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_remove_business_user_staff'),
        ('tutor', '0005_woof_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalwoof',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_woofs', to='pets.business'),
        ),
        migrations.AddField(
            model_name='woof',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_woofs', to='pets.business'),
        ),
    ]
