# Generated by Django 5.2.9 on 2025-12-14 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('reservations', '0002_petreservation_petattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('walk', 'Walk'), ('grooming', 'Grooming'), ('daycare', 'Daycare'), ('pickup', 'Pick-up'), ('dropoff', 'Drop-off'), ('training', 'Training'), ('other', 'Other')], default='walk', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_schedule', to='pets.pet')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.tutor')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
