# Generated by Django 5.2.9 on 2026-01-04 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_remove_business_user_staff'),
        ('reservations', '0004_service_serviceslot_servicebooking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='serviceslot',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_slots', to='pets.business'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceslot',
            unique_together={('business', 'service', 'date', 'start_time')},
        ),
        migrations.CreateModel(
            name='BusinessUnavailableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('closed', 'Fully Closed'), ('half_day', 'Half Day (Reduced Hours)'), ('holiday', 'Holiday'), ('strike', 'Strike'), ('special', 'Special Event')], default='closed', max_length=20)),
                ('reason', models.CharField(blank=True, help_text="e.g., 'Christmas', 'Staff training', 'Emergency closure'", max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_days', to='pets.business')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('business', 'date')},
            },
        ),
    ]
