# Generated by Django 5.2.9 on 2026-01-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_businessinquiry'),
    ]

    operations = [
    ]
